### PR TITLE
Support string suffix in addition to prefix

### PR DESCRIPTION
**Pull request by brophdawg11**
Addresses issue #9

### CODE REVIEW

**Comment by Zmetser** [comment]
Thank you!

**Comment by brophdawg11** [comment]
You're welcome!  Could you bump the version for bower, or if it's easier, I can open a PR for that?

**Comment by Zmetser** [comment]
Thanks for the reminder @brophdawg11 It's taken care of: https://github.com/Zmetser/angular-currency-filter/releases/tag/v2.2.0

**Comment by brophdawg11** [comment]
Thanks!

**Pull request merged**
